make stop_api
CodeGateCircle/subscription_app_back pull request #10
Opened 2022-09-28 07:52 UTC by yamato-1205

2022-09-28 08:09 UTC, taisei1989 commented
ゆずくん返信できないかもなので山下観点で気になったポイント書いとくね

2022-09-28 11:25 UTC, yuzuki-aritomo reviewed
Is_stop的なカラムにして欲しい！

2022-10-04 12:35 UTC, yuzuki-aritomo approved these changes
👍🏻

2022-10-04 12:38 UTC, yuzuki-aritomo requested changes
openAPIの方も`isPause`に変更してほしい 🙏🏻

2022-10-06 04:39 UTC, merged